/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion.lineal;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Interface_Restrictions extends javax.swing.JFrame {
    
    Interface_Main interfaz_principal;
    ArrayList<ArrayList<Double>> matriz_valores_restricciones; //NºFilas = Nº de restricciones; NºColumnas = Nº de variables.
    
    /**
     * Creates new form Interface_Restrictions
     */
    public Interface_Restrictions() {
        initComponents();
    }
    
    public void setRestricciones(Interface_Main i){
        interfaz_principal = i;
        matriz_valores_restricciones = new ArrayList<>();
        for (int f = 0; f < interfaz_principal.get_NumRestricciones(); f++) {
            matriz_valores_restricciones.add(f, new ArrayList<>());
            for (int c = 0; c < interfaz_principal.get_NumVarDecision(); c++) {
                matriz_valores_restricciones.get(f).add(c, 0.0);
            }
        }
        
    }
    
    public void rellenaRestricciones(){
        //TODO: AÑADIR UNA TABLA DE FORMA QUE SE PUEDA AÑADIR LAS RESTRICCIONES SIN PROBLEMAS
        // - USAR LA TABLA PARA PONER EN LOS HUECOS EL VALOR DE LA Xi e INDICAR EL <= (YA PUESTO) Y A LA DERECHA OTRO HUECO PA QUE PONGAN EL VALOR.
        generarMatriz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Restrictions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Restrictions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Restrictions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Restrictions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Restrictions().setVisible(true);
            }
        });
    }

    
    private void generarMatriz(){
        DefaultTableModel tabla_auxiliar = new DefaultTableModel();
            
            tabla_auxiliar.addColumn("coef. en Z");
            tabla_auxiliar.addColumn("V.B.");
            tabla_auxiliar.addColumn("b");
            for (int i = 0; i < interfaz_principal.get_NumRestricciones()*2; i++)
                tabla_auxiliar.addColumn("x"+(i+1));
            tabla_auxiliar.addColumn("b/a (a >= 0)");
            
            for (int i = 0; i < interfaz_principal.get_NumRestricciones()+1; i++) {
                tabla_auxiliar.addRow(new Object[tabla_auxiliar.getColumnCount()]);
                if (i < interfaz_principal.get_NumRestricciones()){
                    tabla_auxiliar.setValueAt(0, i, 0);
                    tabla_auxiliar.setValueAt("x"+(i+interfaz_principal.get_NumRestricciones()), i, 1);
                }
            }
//            for (int i = 0; i < tabla_auxiliar.getRowCount(); i++) {
//                for (int j = 0; j < tabla_auxiliar.getColumnCount(); j++) {
//                    if (i == j) {
//                        tabla_auxiliar.setValueAt(1, i, j + 1);
//                    }
//                }
//            }

            jTable1.setModel(tabla_auxiliar);
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
